name: "Configure gradle"
description: ""

inputs:
  java-version:
    description: "Java Version"
    default: "17"
  distribution:
    description: "Java Distribution"
    default: "temurin"

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}

    - name: Gradle
      uses: gradle/actions/setup-gradle@v4